development:
  adapter:  mysql2
  encoding: utf8
  database: left_right_dev
  username: root
  password: yoshi
  host:     127.0.0.1
  port:     3306

test:
  adapter:  mysql2
  encoding: utf8
  database: left_right_test
  username: root
  password: yoshi
  host:     127.0.0.1
  port:     3306

production:
  adapter:  mysql2
  encoding: utf8
  database: left_right
  username: root
  password: yoshi
  host:     127.0.0.1
  port:     3306